Update build-padavan.yml

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -40,6 +40,12 @@ jobs:
       env:
         TNAME: GHL
       run: |
+        cd /opt/rt-n56u/trunk/user/htop
+        wget -t5 --timeout=20 --no-check-certificate -O htop-3.0.2.tar.gz https://github.com/hanwckf/rt-n56u/raw/master/trunk/user/htop/htop-3.0.2.tar.gz
+         if [ ! -f htop-3.0.2.tar.gz ] ; then
+         echo "htop-3.0.2.tar.gz not found "
+		     exit 1 
+         fi
         cd /opt/rt-n56u/trunk
         if [ ! -f configs/templates/$TNAME.config ] ; then
         echo "configs/templates/$TNAME.config not found "
